In [1]:
from typing import Any, Optional
import numpy as np
import pandas as pd
import geopandas as gpd
import shapely
from multiprocesspandas import applyparallel
from tqdm.notebook import trange, tqdm, trange
tqdm.pandas()
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:postgres@10.32.1.107/city_db_final")
import osmnx as ox 
import networkx as nx
import networkit as nk
#import graph_tool
#from graph_tool.all import * 
import pulp
import multiprocessing as mp
import os
import rpyc 
import pickle
import os
import sys
import copy
import json
import requests
import pyproj
folder = "/var/essdata/IDU/aantonov/CityGeoTools"
sys.path.append(folder)

from metrics.data import CityInformationModel as BaseModel
city_model = BaseModel.CityInformationModel(
city_name="saint-petersburg", city_crs=32636, cities_db_id=1, mode="general_mode", cwd="./", 
rpyc_adr="10.32.1.65", rpyc_port=18867, postgres_con="postgresql://postgres:postgres@10.32.1.107/city_db_final")

from data_collecting.get_graphs import get_osmnx_graph
from metrics.calculations import CityMetricsMethods as Metrics

/var/essdata/IDU/aantonov/ant_env/lib/python3.9/site-packages/geopandas/_compat.py:112: UserWarning: The Shapely GEOS version (3.10.3-CAPI-1.16.1) is incompatible with the GEOS version PyGEOS was compiled with (3.10.1-CAPI-1.16.0). Conversions between both will be slow.
  warnings.warn(


saint-petersburg MobilityGraph
saint-petersburg Buildings
saint-petersburg Services
saint-petersburg PublicTransportStops
saint-petersburg ServiceTypes
saint-petersburg RecreationalAreas
saint-petersburg Blocks
saint-petersburg Municipalities
saint-petersburg AdministrativeUnits


In [2]:
urban_quality_test = Metrics.Urban_Quality(city_model).get_urban_quality(city_model, get_index=True)

Indicator 1 done
Indicator 2 done
Indicator 4 done
Indicator 5 done
Indicator 10 done
Indicator 14 done
Indicator 15 done
Indicator 17 done
Indicator 22 done
Indicator 23 done
urban quality index ready


In [9]:
urban_quality_test

id           area  municipality_id  administrative_unit_id  \
0        2  266719.332742             79.0                    48.0   
1        3   54966.155200             84.0                    58.0   
2        4  166108.341737             29.0                    63.0   
3        5   39814.183158             73.0                    59.0   
4        6   13577.028284             67.0                    58.0   
...    ...            ...              ...                     ...   
5572  6306   37400.522277             11.0                    63.0   
5573  6307    9677.417712             71.0                    58.0   
5574  6308   36040.335454             83.0                    63.0   
5575  6309   11966.875159             20.0                    46.0   
5576  6310   17389.650358             43.0                    59.0   

                                               geometry  ind1  ind2  ind4  \
0     MULTIPOLYGON (((348127.253 6655861.068, 347936...  10.0  10.0   1.0   
1     MULTIPOLYGON (((353093.401 6646363.804, 353017...  10.0  10.0   0.0   
2     MULTIPOLYGON (((350927.749 6645270.946, 350842...  10.0   1.0   0.0   
3     MULTIPOLYGON (((349520.559 6651062.524, 349514...  10.0   1.0   1.0   
4     MULTIPOLYGON (((352709.915 6647835.049, 352544...  10.0   9.0   1.0   
...                                                 ...   ...   ...   ...   
5572  MULTIPOLYGON (((348904.054 6646883.597, 349168...   0.0   0.0   0.0   
5573  MULTIPOLYGON (((352537.799 6647764.876, 352534...   0.0   0.0   0.0   
5574  MULTIPOLYGON (((348892.457 6644868.211, 349341...   0.0   0.0   0.0   
5575  MULTIPOLYGON (((350459.299 6656350.126, 350444...   0.0   0.0   0.0   
5576  MULTIPOLYGON (((349348.322 6650386.333, 349392...   0.0   0.0   0.0   

      ind5  ind10  ind14  ind15  ind17  ind22  ind23  urban_quality_value  
0      1.0    1.0    0.0    0.0    1.0    0.0    1.0                  1.0  
1      1.0    3.0    0.0    0.0    0.0    0.0    1.0                  3.0  
2      1.0    2.0    0.0    0.0    1.0    1.0    1.0                  1.0  
3      1.0    1.0    0.0    0.0    0.0    0.0    1.0                  1.0  
4      1.0    2.0    0.0    0.0    1.0    0.0    1.0                  1.0  
...    ...    ...    ...    ...    ...    ...    ...                  ...  
5572   0.0    0.0    0.0    0.0    0.0    0.0    0.0                  0.0  
5573   0.0    0.0    0.0    0.0    0.0    0.0    0.0                  0.0  
5574   0.0    0.0    0.0    0.0    0.0    0.0    0.0                  0.0  
5575   0.0    0.0    0.0    0.0    0.0    0.0    0.0                  0.0  
5576   0.0    0.0    0.0    0.0    0.0    0.0    0.0                  0.0  

[5564 rows x 16 columns]

In [6]:
test_blocks = city_model.Blocks.copy()
test_blocks['IND'], test_blocks['IND_data'] = Metrics.Urban_Quality(city_model).ind2()

Indicator 2 done


In [7]:
test_blocks

id           area  municipality_id  administrative_unit_id  \
0        2  266719.332742             79.0                    48.0   
1        3   54966.155200             84.0                    58.0   
2        4  166108.341737             29.0                    63.0   
3        5   39814.183158             73.0                    59.0   
4        6   13577.028284             67.0                    58.0   
...    ...            ...              ...                     ...   
5572  6306   37400.522277             11.0                    63.0   
5573  6307    9677.417712             71.0                    58.0   
5574  6308   36040.335454             83.0                    63.0   
5575  6309   11966.875159             20.0                    46.0   
5576  6310   17389.650358             43.0                    59.0   

                                               geometry  IND  IND_data  
0     MULTIPOLYGON (((348127.253 6655861.068, 347936...   10  1.000000  
1     MULTIPOLYGON (((353093.401 6646363.804, 353017...   10  0.946372  
2     MULTIPOLYGON (((350927.749 6645270.946, 350842...    1  0.000000  
3     MULTIPOLYGON (((349520.559 6651062.524, 349514...    1  0.000000  
4     MULTIPOLYGON (((352709.915 6647835.049, 352544...    9  0.859120  
...                                                 ...  ...       ...  
5572  MULTIPOLYGON (((348904.054 6646883.597, 349168...    0       NaN  
5573  MULTIPOLYGON (((352537.799 6647764.876, 352534...    0       NaN  
5574  MULTIPOLYGON (((348892.457 6644868.211, 349341...    0       NaN  
5575  MULTIPOLYGON (((350459.299 6656350.126, 350444...    0       NaN  
5576  MULTIPOLYGON (((349348.322 6650386.333, 349392...    0       NaN  

[5564 rows x 7 columns]

Далее черновик кода

In [2]:
drive_G = nx.Graph(((u, v, e) for u,v,e in city_model.MobilityGraph.edges(data=True) if e['type'] == 'car'))

In [3]:
input_pol = gpd.read_file('/var/essdata/IDU/aantonov/input_vo.geojson').geometry.iloc[0]

In [3]:
social_services = pd.read_sql(f'''SELECT * FROM maintenance.social_groups_city_service_types''', con=engine)
street_services = pd.read_csv('/var/essdata/IDU/aantonov/pog_services.csv', sep=';', index_col='id')
main_services_id = social_services.groupby('city_service_type_id').nunique().sort_values(by='social_group_id')
main_services_id = main_services_id[main_services_id['social_group_id'] == 11].reset_index()
main_services = city_model.Services[city_model.Services.city_service_type_id.isin(main_services_id.city_service_type_id)]
main_services = list(pd.unique(main_services.service_code))
street_services = city_model.Services[city_model.Services.city_service_type.isin(street_services.city_service_type)]
street_services = list(pd.unique(street_services.service_code))
cultural_services = ['art_spaces', 'libraries', 'theaters', 'museums', 'shopping_centers', 'cinemas', 'bars',
 'bakeries', 'cafes', 'restaurants', 'fastfoods', 'zoos', 'bowlings']
sport_services = ['sportgrounds', 'swimming_pools', 'sport_centers', 'stadiums', 'fitness_clubs', 'sport_clubs', 'aquaparks']

In [4]:
def ind1(buildings, blocks):
    '''
    :param buildings_file: file with buildings, attributes 'failure' and 'living_area' needed --> str
    :param blocks_file: file with city blocks, block id needed --> str
    :return: GeoJSON with column with indicator 1 (IND1)
    '''
    local_buildings = copy.deepcopy(buildings)
    local_blocks = copy.deepcopy(blocks)

    normal_buildings = local_buildings.dropna(subset=['is_emergency'])
    emergent_buildings = normal_buildings.query('is_emergency')

    local_blocks['emergent_living_area'] = local_blocks.merge(emergent_buildings.groupby(['block_id'])\
        .sum().reset_index(), how='left', left_on='id', right_on='block_id')['living_area']
    local_blocks['living_area'] = local_blocks.merge(normal_buildings.groupby(['block_id'])\
        .sum().reset_index(), how='left', left_on='id', right_on='block_id')['living_area']
    local_blocks.loc[(local_blocks.living_area.notnull() & local_blocks.emergent_living_area.isnull()), 'emergent_living_area'] = 0
    local_blocks['IND_data'] = (local_blocks['living_area'] - local_blocks['emergent_living_area']) / local_blocks['living_area']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 1 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind2(buildings, blocks):
    '''
    :param buildings_file: file with buildings, attributes 'central_heating', 'central_hot_water', 'central electricity', 'central_gas' and 'living_area' needed --> str
    :param blocks_file: file with city blocks, block id needed --> str
    :return: GeoJSON with column with indicator 2 (IND2)
    '''
    local_blocks = copy.deepcopy(blocks)
    local_buildings = copy.deepcopy(buildings)

    normal_buildings = local_buildings.dropna(subset=['central_heating', 'central_hotwater'])
    normal_buildings = normal_buildings.dropna(subset=['central_electro', 'central_gas'], how='all')

    accomodated_buildings = normal_buildings.query('central_heating & central_hotwater & (central_electro | central_gas)')

    normal_buildings_in_blocks = normal_buildings.groupby('block_id').sum().reset_index()
    accomodated_buildings_in_blocks = accomodated_buildings.groupby('block_id').sum().reset_index()
    local_blocks['normal_living_area'] = local_blocks.merge(normal_buildings_in_blocks,\
         how='left', left_on='id', right_on='block_id')['living_area']
    local_blocks['accomodated_living_area'] = local_blocks.merge(accomodated_buildings_in_blocks,\
         how='left', left_on='id', right_on='block_id')['living_area']

    local_blocks.loc[(local_blocks.normal_living_area.notnull() & local_blocks.accomodated_living_area.isnull()), 'accomodated_living_area'] = 0
    local_blocks['IND_data'] = local_blocks['accomodated_living_area'] / local_blocks['normal_living_area']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 2 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind4(buildings, blocks):
    '''
    :param buildings_file: file with buildings, attributes 'is_living', 'building_year', 'project_type' needed --> str
    :param blocks_file: file with city blocks, block id needed --> str
    :return: GeoJSON with column with indicator 4 (IND4)
    '''
    houses = copy.deepcopy(buildings)[buildings['is_living']]
    local_blocks = copy.deepcopy(blocks)
    modern_houses = houses.query('1956 <= building_year')

    modern_houses_diversity = modern_houses.groupby('block_id').agg({'id':'size', 'project_type':'nunique'}).reset_index()
    modern_houses_diversity['total_count'] = modern_houses_diversity.merge\
        (houses.groupby('block_id').count().reset_index())['id']
    modern_houses_diversity['project_type'].replace(0, 1, inplace=True)
    modern_houses_diversity['weighted_diversity'] = (modern_houses_diversity.project_type / modern_houses_diversity.total_count)

    local_blocks['IND_data'] = local_blocks.merge(modern_houses_diversity,\
         how='left', left_on='id', right_on='block_id')['weighted_diversity']
    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 4 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind5(services, buildings, blocks, services_list):
    local_blocks = copy.deepcopy(blocks)
    houses = copy.deepcopy(buildings).query('is_living')
    local_services = copy.deepcopy(services)
    local_services = local_services[local_services['service_code'].isin(main_services)]

    count_in_blocks = local_services.groupby('block_id').count().reset_index()
    count_in_blocks['IND_data'] = count_in_blocks['id']/count_in_blocks['building_id']
    count_in_blocks = count_in_blocks[(count_in_blocks.IND_data != np.inf) &\
        (count_in_blocks.block_id.isin(pd.unique(houses.block_id)))]

    local_blocks['IND_data'] = local_blocks.merge(count_in_blocks,\
        how='left', left_on='id', right_on='block_id')['IND_data']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 5 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind10(services, buildings, blocks, street_graph, service_list):

    def get_links(street_graph):
        links = nx.to_pandas_edgelist(street_graph)
        links['geometry'] = gpd.GeoSeries.from_wkt(links['geometry'])
        links = gpd.GeoDataFrame(links, geometry='geometry').set_crs(32636)
        return links

    local_blocks = copy.deepcopy(blocks)
    local_buildings = copy.deepcopy(buildings)
    local_services = copy.deepcopy(services)
    local_services = local_services[local_services['service_code'].isin(service_list)]
    walk_links = get_links(street_graph)

    walk_links['geometry'] = walk_links.geometry.buffer(40)
    walk_links['link_id'] = walk_links.index

    #Arguments
    links_with_objects = gpd.sjoin(walk_links, local_buildings[['geometry', 'id']], how='inner')
    walk_links['n_buildings'] = walk_links.merge(links_with_objects.groupby('link_id').count().reset_index(), on='link_id', how='left')['id'].dropna()

    links_with_objects = gpd.sjoin(walk_links, local_services[['geometry', 'city_service_type', 'id']], how='inner')
    walk_links['n_services'] = walk_links.merge(links_with_objects.groupby('link_id').count().reset_index(), on='link_id', how='left')['id'].fillna(0)
    walk_links['n_types_services'] = walk_links.merge(links_with_objects.groupby('link_id').nunique()['city_service_type'].reset_index(), how='left')['city_service_type'].fillna(0)

    #Indicators
    N_types = len(pd.unique(services.city_service_type))
    walk_links['variety'] = (walk_links['n_types_services']/N_types)
    walk_links['density'] = ((walk_links['n_services']/walk_links['length_meter'])*100)
    walk_links['saturation'] = (walk_links['n_services']/walk_links['n_buildings'])

    # Maturity
    walk_links['maturity'] = (0.5*walk_links['variety'] + 0.25*walk_links['density'] + 0.25*walk_links['saturation'])

    walk_links_with_blocks = gpd.sjoin(local_blocks[['geometry', 'id']], walk_links[['geometry', 'maturity']], how='inner')
    local_blocks['IND_data'] = local_blocks.merge(walk_links_with_blocks.groupby('id').mean().reset_index(), how='left')['maturity']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 10 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind11(buildings, blocks):
     
     def get_walk_isochrone(location):
        walk_accessibility_zone = Metrics.AccessibilityIsochrones(city_model).get_accessibility_isochrone(
                travel_type="walk",
                x_from=location['x'], 
                y_from=location['y'],
                weight_type = "length_meter",
                weight_value = 800)
        isochrone_geometry = gpd.GeoDataFrame.from_features(walk_accessibility_zone["isochrone"])\
                .set_crs(4326).to_crs(32636)
        return isochrone_geometry
     
     local_blocks = copy.deepcopy(blocks)
     houses = copy.deepcopy(buildings[buildings.is_living])

     isochrones = houses.apply_parallel(get_walk_isochrone).reset_index()
     isochrones['isochrones_area'] = isochrones.area
     houses = houses.merge(isochrones, how='inner', left_on=houses.index, right_on='level_0')
     local_blocks['IND_data'] = local_blocks.merge(houses.groupby('block_id').mean().reset_index(),\
          left_on='id', right_on='block_id', how='left')['isochrones_area']

     local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
     local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
     print('Indicator 11 done')

     return local_blocks['IND'], local_blocks['IND_data']

def ind13(blocks):
    local_blocks = copy.deepcopy(blocks)

    Provisions_class = Metrics.City_Provisions(city_model,
                                   service_types = ['recreational_areas'],
                                   valuation_type = "model",
                                   year = 2022, 
                                   user_changes_buildings = None,
                                   user_changes_services = None,
                                   user_provisions = None,
                                   user_selection_zone = None,
                                   service_impotancy = None)
    g_provision = Provisions_class.get_provisions()
    greenery_in_use = gpd.GeoDataFrame.from_features(g_provision['services']['features'])
    greenery_in_use['efficiency'] = greenery_in_use['service_load'] / greenery_in_use['capacity']
    local_blocks['IND_data'] = local_blocks.merge(greenery_in_use.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['efficiency']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 13 done')

    return local_blocks['IND'], local_blocks['IND_data']

def ind14_15(blocks, greenery):
    '''
    :param blocks: file with city blocks, block id needed --> str
    :param greenery: file with polygons of greenery with NDVI index --> str
    :return: GeoJSON with column with indicator 14 and indicator 15 (IND14-15)
    '''
    local_blocks = copy.deepcopy(blocks)

    local_blocks['area'] = local_blocks.area
    greenery_in_blocks = gpd.overlay(local_blocks, greenery, how='intersection')
    greenery_in_blocks['green_area'] = greenery_in_blocks.area
    share_of_green = greenery_in_blocks.groupby(['block_id', 'vegetation_index']).sum('green_area').reset_index()
    share_of_green['share'] = share_of_green['green_area'] / share_of_green['area']
    share_of_green['vw'] = share_of_green.vegetation_index.astype(float) * share_of_green.share.astype(float)

    share_of_green_grouped = share_of_green.groupby('block_id').sum().reset_index()
    share_of_green_grouped['quality'] = share_of_green_grouped.vw / share_of_green_grouped.share

    local_blocks[['IND_14_data', 'IND_15_data']]  = local_blocks.merge(share_of_green_grouped, how='left')[['share', 'quality']] 

    local_blocks['IND_14'] = pd.cut(local_blocks['IND_14_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND_14'] = pd.to_numeric(local_blocks['IND_14']).fillna(0).astype(int)
    print('Indicator 14 done')
    local_blocks['IND_15'] = pd.cut(local_blocks['IND_15_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND_15'] = pd.to_numeric(local_blocks['IND_15']).fillna(0).astype(int)
    print('Indicator 15 done')
    return local_blocks['IND_14'], local_blocks['IND_14_data'], local_blocks['IND_15'], local_blocks['IND_15_data']

def ind17(blocks, greenery, services, service_list):

    local_blocks = copy.deepcopy(blocks)

    local_services = copy.deepcopy(services)
    local_services = local_services[local_services['service_code'].isin(service_list)]

    local_greenery = copy.deepcopy(greenery)

    greenery_in_blocks = gpd.overlay(local_blocks, local_greenery[['geometry', 'service_code', 'block_id']], how='intersection')
    greenery_in_blocks['green_area'] = greenery_in_blocks.area

    services_in_greenery = gpd.sjoin(greenery_in_blocks, local_services['geometry'].reset_index(), how='inner')
    services_in_greenery = services_in_greenery.groupby(['id', 'block_id', 'green_area']).count().reset_index()
    services_in_greenery = services_in_greenery.groupby('block_id').sum().reset_index()
    services_in_greenery['weighted_service_count'] = services_in_greenery['id'] / services_in_greenery['green_area']

    local_blocks['IND_data'] = local_blocks.merge(services_in_greenery,\
            left_on='id', right_on='block_id', how='left')['weighted_service_count']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 17 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind18(blocks):
    local_blocks = copy.deepcopy(blocks)
    Provisions_class = Metrics.City_Provisions(city_model,
                                   service_types = ['recreational_areas'],
                                   valuation_type = "model",
                                   year = 2022, 
                                   user_changes_buildings = None,
                                   user_changes_services = None,
                                   user_provisions = None,
                                   user_selection_zone = None,
                                   service_impotancy = None)
    g_provision = Provisions_class.get_provisions()
    greenery_provision = gpd.GeoDataFrame.from_features(g_provision['houses']['features'])

    local_blocks['IND_data'] = local_blocks.merge(greenery_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['recreational_areas_provison_value']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 18 done')
    return local_blocks['IND'], local_blocks['IND_data']
    
def ind20(buildings, blocks, service_list):
    local_buildings = copy.deepcopy(buildings)
    local_blocks = copy.deepcopy(blocks)
    
    #add total building area
    local_buildings['storeys_count'].fillna(1.0, inplace=True)
    local_buildings['building_area'] = local_buildings['basement_area'] * local_buildings['storeys_count']
    #calculate MXI
    sum_grouper = local_buildings.groupby(["block_id"]).sum().reset_index()
    sum_grouper['MXI'] = sum_grouper["living_area"] / sum_grouper["building_area"]
    local_blocks['MXI'] = local_blocks.merge(sum_grouper, how ='left')['MXI']
    
    #calculate_provision
    Provisions_class = Metrics.City_Provisions(city_model,
                                   service_types = service_list,
                                   valuation_type = "model",
                                   year = 2022, 
                                   user_changes_buildings = None,
                                   user_changes_services = None,
                                   user_provisions = None,
                                   user_selection_zone = None,
                                   service_impotancy = None)
    s_provision = Provisions_class.get_provisions()
    services_provision = gpd.GeoDataFrame.from_features(s_provision['houses']['features'])
    services_provision['mean_provision'] = services_provision.filter(regex='.*_provison_value').mean(axis=1)
    local_blocks['IND_data'] = local_blocks.merge(services_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['mean_provision']
    
    #replace provision in blocks without living houses and with business area >= 0.2 with None
    local_blocks.loc[local_blocks.index.isin(local_blocks.query('0 < MXI <= 0.8').index), 'IND_data'] = None

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 20 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind22(blocks, services):
    '''
    :param blocks: file with city blocks, block id needed --> str
    :param services: file with okn --> str
    :return: GeoJSON with column with indicator 21 (IND21)
    '''
    local_blocks = copy.deepcopy(blocks)
    local_okn = copy.deepcopy(services)
    local_okn = local_okn[local_okn['service_code'] =='culture_object']

    local_blocks['area'] = local_blocks.area
    okn_in_blocks = gpd.sjoin(local_okn[['geometry', 'service_code']], local_blocks, how='inner')
    local_blocks['n_okn'] = local_blocks.merge(okn_in_blocks.groupby('id').count().reset_index(), on='id', how='left')['service_code']
    local_blocks['IND_data'] = (local_blocks['n_okn'] / local_blocks['area'])

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 22 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind23(blocks, buildings, services):
    local_blocks = copy.deepcopy(blocks)
    local_services = copy.deepcopy(services)
    local_buildings = copy.deepcopy(buildings)
    #add total building area
    local_buildings['storeys_count'].fillna(1.0, inplace=True)
    local_buildings['building_area'] = local_buildings['basement_area'] * local_buildings['storeys_count']
    #calculate MXI
    sum_grouper = local_buildings.groupby(["block_id"]).sum().reset_index()
    sum_grouper['MXI'] = sum_grouper["living_area"] / sum_grouper["building_area"]
    sum_grouper = sum_grouper.query('0 < MXI <= 0.8')
    #filter commercial services
    local_services = local_services[local_services['service_code'].isin(main_services)]
    #calculate free area for commercial services
    sum_grouper['commercial_area'] = sum_grouper['building_area'] - sum_grouper['living_area'] - sum_grouper['building_area']*0.1
    #calculate number of commercial services per block
    local_blocks['n_services'] = local_blocks.merge(local_services.groupby('block_id').count().reset_index(),\
        left_on='id', right_on='block_id', how='left')['service_code']
    local_blocks['commercial_area'] = local_blocks.merge(sum_grouper, left_on='id', right_on='block_id', how='left')['commercial_area']
    #calculate commercial diversity
    local_blocks['IND_data'] = (local_blocks['n_services'] / local_blocks['commercial_area'])

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 23 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind25(blocks):
    local_blocks = copy.deepcopy(blocks)
    Provisions_class = Metrics.City_Provisions(city_model,
                                   service_types = ['crosswalks'],
                                   valuation_type = "model",
                                   year = 2022, 
                                   user_changes_buildings = None,
                                   user_changes_services = None,
                                   user_provisions = None,
                                   user_selection_zone = None,
                                   service_impotancy = None)
    crosswalks_provision = Provisions_class.get_provisions()
    crosswalks_provision = gpd.GeoDataFrame.from_features(crosswalks_provision['houses']['features'])

    local_blocks['IND_data'] = local_blocks.merge(crosswalks_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['stops_provison_value']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 25 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind26(blocks, service_list):
    local_blocks = copy.deepcopy(blocks)
    Provisions_class = Metrics.City_Provisions(city_model,
                                    service_types = service_list,
                                    valuation_type = "model",
                                    year = 2022, 
                                    user_changes_buildings = None,
                                    user_changes_services = None,
                                    user_provisions = None,
                                    user_selection_zone = None,
                                    service_impotancy = None)
    local_provision = Provisions_class.get_provisions()
    local_provision = gpd.GeoDataFrame.from_features(local_provision['houses']['features'])


    local_provision['median_provision'] = local_provision.filter(regex='.*_provison_value').median(axis=1)
    local_blocks['IND_data'] = local_blocks.merge(local_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['median_provision']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    return local_blocks['IND'], local_blocks['IND_data']

def ind27(blocks, service_list):
    local_blocks = copy.deepcopy(blocks)
    Provisions_class = Metrics.City_Provisions(city_model,
                                    service_types = sport_services,
                                    valuation_type = "model",
                                    year = 2022, 
                                    user_changes_buildings = None,
                                    user_changes_services = None,
                                    user_provisions = None,
                                    user_selection_zone = None,
                                    service_impotancy = None)
    local_provision = Provisions_class.get_provisions()
    local_provision = gpd.GeoDataFrame.from_features(local_provision['houses']['features'])

    local_blocks['IND_data_1'] = local_blocks.merge(local_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['sportgrounds_provison_value']
    local_provision.drop(columns={'sportgrounds_provison_value'})
    local_provision['median_provision'] = local_provision.filter(regex='.*_provison_value').median(axis=1)
    local_blocks['IND_data_2'] = local_blocks.merge(local_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['median_provision']

    local_blocks['IND_1'] = pd.cut(local_blocks['IND_data_1'], 5, labels=[1, 2, 3, 4, 5], right=False)
    local_blocks['IND_1'] = pd.to_numeric(local_blocks['IND_1']).fillna(0).astype(int)
    local_blocks['IND_2'] = pd.cut(local_blocks['IND_data_2'], 5, labels=[1, 2, 3, 4, 5], right=False)
    local_blocks['IND_2'] = pd.to_numeric(local_blocks['IND_2']).fillna(0).astype(int)
    local_blocks['IND'] = (local_blocks['IND_1'] + local_blocks['IND_2'])
    return local_blocks['IND'], local_blocks['IND_data_1'], local_blocks['IND_data_2']

def ind28(blocks, buildings, services, service_list):
    local_blocks = copy.deepcopy(blocks)
    local_buildings = copy.deepcopy(buildings)
    local_services = copy.deepcopy(services)[services['service_code'].isin(main_services)]
    local_okn = copy.deepcopy(services)[services['service_code'] =='culture_object']
    #filter buildings with services
    local_buildings_in_use = local_buildings[local_buildings['id'].isin(pd.unique(local_services['building_id']))]
    #calculate number of cultural objects in buildings and cult_obj in buildings with services
    local_blocks['n_okn'] = gpd.sjoin(local_buildings, local_okn[['geometry', 'service_code']], how='inner').groupby(['block_id']).count().reset_index()['id']
    local_blocks['n_okn_in_use'] = gpd.sjoin(local_buildings_in_use, local_okn[['geometry', 'service_code']], how='inner').groupby(['block_id']).count().reset_index()['id']
    local_blocks['IND_data'] = (local_blocks['n_okn_in_use'] / local_blocks['n_okn'])

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 28 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind30(blocks):
    local_blocks = copy.deepcopy(blocks)
    Provisions_class = Metrics.City_Provisions(city_model,
                                   service_types = ['kindergartens'],
                                   valuation_type = "normative",
                                   year = 2022, 
                                   user_changes_buildings = None,
                                   user_changes_services = None,
                                   user_provisions = None,
                                   user_selection_zone = None,
                                   service_impotancy = None)
    kindergartens_provision = Provisions_class.get_provisions()
    kindergartens_provision = gpd.GeoDataFrame.from_features(kindergartens_provision['houses']['features'])

    local_blocks['IND_data'] = local_blocks.merge(kindergartens_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['kindergartens_provison_value']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 30 done')
    return local_blocks['IND'], local_blocks['IND_data']

def ind32(blocks):
    local_blocks = copy.deepcopy(blocks)
    Provisions_class = Metrics.City_Provisions(city_model,
                                   service_types = ['stops'],
                                   valuation_type = "model",
                                   year = 2022, 
                                   user_changes_buildings = None,
                                   user_changes_services = None,
                                   user_provisions = None,
                                   user_selection_zone = None,
                                   service_impotancy = None)
    stops_provision = Provisions_class.get_provisions()
    stops_provision = gpd.GeoDataFrame.from_features(stops_provision['houses']['features'])

    local_blocks['IND_data'] = local_blocks.merge(stops_provision.groupby('block_id').mean().reset_index(),\
        left_on='id', right_on='block_id', how='left')['stops_provison_value']

    local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
    local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
    print('Indicator 32 done')
    return local_blocks['IND'], local_blocks['IND_data']

In [ ]:
# ########################################   IPI  ####################################################

class urban_quality(BaseMethod):

    def __init__(self, city_model):
        BaseMethod.__init__(self, city_model)
        self.buildings = city_model.Buildings.copy()
        self.services = city_model.Services.copy()
        self.blocks = city_model.Blocks.copy()
        self.greenery = city_model.RecreationalAreas.copy()
        
        services_in_use = pd.read_sql('''SELECT * FROM maintenance.social_groups_city_service_types''', con=engine)
        main_services_id = services_in_use.groupby('city_service_type_id').nunique().sort_values(by='social_group_id')
        main_services_id = main_services_id[main_services_id['social_group_id'] == 11].reset_index()
        main_services = [city_model.Services.city_service_type_id.isin(main_services_id.city_service_type_id)]
        self.main_services = list(pd.unique(main_services.service_code))
        self.street_services_id = [31, 181, 88, 20, 25, 87, 28, 30, 60, 27, 86, 18, 90, 62, 83, 47, 17, 63, 39,
        22, 163, 84, 32, 15, 24, 26, 46, 11, 53, 190, 172, 89, 92, 29, 48, 81, 161, 162, 147, 165, 148, 170, 168, 37, 178,
        54, 179, 51, 156, 169, 176]
        self.drive_graph = nx.Graph(((u, v, e) for u,v,e in city_model.MobilityGraph.edges(data=True) if e['type'] == 'car'))

    def ipi1(self):
        local_blocks = self.blocks
        Provisions_class = Metrics.City_Provisions(city_model,
                                    service_types = ['schools'],
                                    valuation_type = "normative",
                                    year = 2022, 
                                    user_changes_buildings = None,
                                    user_changes_services = None,
                                    user_provisions = None,
                                    user_selection_zone = None,
                                    service_impotancy = None)
        kindergartens_provision = Provisions_class.get_provisions()
        kindergartens_provision = gpd.GeoDataFrame.from_features(kindergartens_provision['houses']['features'])

        local_blocks['IND_data'] = local_blocks.merge(kindergartens_provision.groupby('block_id').mean().reset_index(),\
            left_on='id', right_on='block_id', how='left')['kindergartens_provison_value']

        local_blocks['IND'] = pd.cut(local_blocks['IND_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
        local_blocks['IND'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
        print('Indicator 30 done')
        return local_blocks['IND'], local_blocks['IND_data']

    def ipi2(self):
        local_blocks = self.blocks
        Provisions_class = Metrics.City_Provisions(city_model,
                                    service_types = ['kindergartens'],
                                    valuation_type = "normative",
                                    year = 2022, 
                                    user_changes_buildings = None,
                                    user_changes_services = None,
                                    user_provisions = None,
                                    user_selection_zone = None,
                                    service_impotancy = None)
        kindergartens_provision = Provisions_class.get_provisions()
        kindergartens_provision = gpd.GeoDataFrame.from_features(kindergartens_provision['houses']['features'])

        local_blocks['IPI_data'] = local_blocks.merge(kindergartens_provision.groupby('block_id').mean().reset_index(),\
            left_on='id', right_on='block_id', how='left')['kindergartens_provison_value']

        local_blocks['IPI'] = pd.cut(local_blocks['IPI_data'], 10, labels=[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], right=False)
        local_blocks['IPI'] = pd.to_numeric(local_blocks['IND']).fillna(0).astype(int)
        print('Indicator 30 done')
        return local_blocks['IPI'], local_blocks['IPI_data']

    def ipi8(self):
        '''
        :param blocks: file with city blocks, block id needed --> str
        :param greenery: file with polygons of greenery with NDVI index --> str
        '''
        local_blocks = self.blocks
        local_greenery = self.greenery

        local_blocks.geometry = local_blocks.centroid.buffer(1000)
        greenery_in_blocks = gpd.overlay(local_blocks, greenery, how='intersection')
        greenery_in_blocks['green_area'] = greenery_in_blocks.area

        local_blocks['IPI_data'] = local_blocks.merge(greenery_ib_blocks.groupby('block_id').sum().reset_index()['green_area'],\
         left_on='id', right_on='block_id', how='left')
        local_blocks['IPI'] = pd.cut(local_blocks['IPI_data'], 5, labels=[1, 2, 3, 4, 5], right=False) 
        local_blocks['IPI'] = pd.to_numeric(local_blocks['IPI5']).fillna(0).astype(int)

        return local_blocks['IPI'], local_blocks['IPI_data']


In [5]:
blocks = city_model.Blocks
buildings = city_model.Buildings
services = city_model.Services
greenery = city_model.RecreationalAreas

In [6]:
blocks.to_crs(4326).to_file('blocks.geojson', driver='GeoJSON')
buildings.to_crs(4326).to_file('buildings.geojson', driver='GeoJSON')
services.to_crs(4326).to_file('services.geojson', driver='GeoJSON')
greenery.to_crs(4326).to_file('greenery.geojson', driver='GeoJSON')

In [6]:
urban_quality = copy.deepcopy(blocks)
urban_quality_raw = copy.deepcopy(blocks)

In [11]:
urban_quality['ind1'], urban_quality_raw['ind1'] = ind1(buildings, blocks)
urban_quality['ind2'], urban_quality_raw['ind2'] = ind2(buildings, blocks)
urban_quality['ind4'], urban_quality_raw['ind4'] = ind4(buildings, blocks)
urban_quality['ind5'], urban_quality_raw['ind5'] = ind5(services, buildings, blocks, main_services)
urban_quality['ind10'], urban_quality_raw['idn10'] = ind10(services, buildings, blocks, drive_G, street_services)
#urban_quality['ind11'], urban_quality_raw['ind11'] = ind11(buildings, blocks) #too long >15 min
#urban_quality['ind13'], urban_quality_raw['ind13'] = ind13(blocks) #recreational areas problem
urban_quality['ind14'], urban_quality_raw['ind14'],\
     urban_quality['ind15'], urban_quality_raw['ind15'] = ind14_15(blocks, greenery)
urban_quality['ind17'], urban_quality_raw['ind17'] = ind17(blocks, greenery, services, main_services)
#urban_quality['ind18'], urban_quality_raw['ind18'] = ind18(blocks) #recreational areas problem
#urban_quality['ind20'], urban_quality_raw['ind20'] = ind20(buildings, blocks, main_services) #too much in RAM
urban_quality['ind22'], urban_quality_raw['ind22'] = ind22(blocks, services)
urban_quality['ind23'], urban_quality_raw['ind23'] = ind23(blocks, buildings, services)
#urban_quality['ind25'], urban_quality_raw['ind25'] = ind25(blocks) #no crosswalks provision in database
urban_quality['ind26'], urban_quality_raw['ind26'] = ind26(blocks, cultural_services)
urban_quality['ind27'], urban_quality_raw['ind27_1'], urban_quality_raw['ind27_2'] = ind27(blocks, sport_services)
urban_quality['ind28'], urban_quality_raw['ind28'] = ind28(blocks, buildings, services, main_services)
urban_quality['ind30'], urban_quality_raw['ind30'] = ind30(blocks)
#urban_quality['ind32'], urban_quality_raw['ind32'] = ind32(blocks) #no stops provision in database

Indicator 1 done
Indicator 2 done
Indicator 4 done
Indicator 5 done
Indicator 10 done
Indicator 14 done
Indicator 15 done
Indicator 17 done
Indicator 22 done
Indicator 23 done
art_spaces not loaded
3809634.0 3453 30.0
3806181.0 0.0 60.0
libraries not loaded
1832017.0 21593 30.0
['', '', 'dummy']
1810424.0 0.0 240.0
theaters not loaded
4187516.0 41098 50.0
4146418.0 0.0 200.0
museums not loaded
4546381.0 956204 50.0
3590177.0 0.0 800.0
shopping_centers not loaded
4546391.0 2607298 30.0
1939093.0 0.0 480.0
cinemas not loaded
4546381.0 48596 60.0
4497785.0 0.0 120.0
bars not loaded
2654486.0 167638 1000.0
2486848.0 0.0 16000.0
bakeries not loaded
4546388.0 220896 1000.0
4325492.0 0.0 16000.0
cafes not loaded
4400455.0 671667 1000.0
3728788.0 0.0 32000.0
restaurants not loaded
3949434.0 272825 20.0


In [42]:
urban_quality = urban_quality.replace(0, np.NaN)
urban_quality['urban_quality_value'] = urban_quality.filter(regex='ind.*').mean(axis=1).round(0)
urban_quality = urban_quality.fillna(0)

In [105]:
for column in urban_quality.columns[6:]:
    print(column)
    print(pd.unique(urban_quality[column]))
    print('--------------------')

ind2
[10.  1.  9.  5.  7.  2.  0.  8.  3.  4.  6.]
--------------------
ind4
[ 1.  0.  2.  8.  4.  7.  3. 10.  5.  6.]
--------------------
ind5
[ 1.  0.  2.  4.  3.  5.  6. 10.  7.]
--------------------
ind10
[6. 0.]
--------------------
ind14
[ 0.  1.  4. 10.  5.  2.  8.  3.  6.  7.  9.]
--------------------
ind15
[ 0.  3.  5.  1.  2.  7.  8.  9.  6.  4. 10.]
--------------------
ind17
[ 1.  0.  2. 10.  3.]
--------------------
ind22
[ 0.  1.  2.  3. 10.]
--------------------
ind23
[ 1.  0. 10.  2.]
--------------------
ind28
[ 1.  2.  3. 10.  4.  5.  8.  0.]
--------------------
ind30
[ 9.  1.  2. 10.  0.  3.  7.  8.  6.  4.  5.]
--------------------
urban_quality_value
[4. 3. 6. 5. 2. 7. 1. 9. 8. 0.]
--------------------
